Repository jaegertracing/jaeger-ui, pull requests merged in 2023-12, with the labels that each got.

#2020 Prepare release 1.36.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2028 Add exact phrase search syntax
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/TracePageSearchBar.tsx
  packages/jaeger-ui/src/utils/filter-spans.test.js
  packages/jaeger-ui/src/utils/filter-spans.tsx
Labels: changelog:new-feature

#2042 Replace Reselect with Memoize
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/DependencyGraph/index.jsx
  packages/jaeger-ui/src/selectors/dependencies.js
  packages/jaeger-ui/tsconfig.lint.json
  yarn.lock
Labels: changelog:dependencies

#2041 Chore: Import only lodash submodules
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/generateDropdownValue.tsx
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.tsx
Labels: changelog:bugfix-or-minor-feature

#2057 Change dependabot frequency to weekly
  .github/dependabot.yml
Labels: changelog:dependencies

#1981 Refactoring: DAG migrated to Plexus's Digraph
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/DependencyGraph/DAG.jsx
  packages/jaeger-ui/src/components/DependencyGraph/DAG.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAG.tsx
  packages/jaeger-ui/src/components/DependencyGraph/dag.css
  packages/jaeger-ui/tsconfig.lint.json
  packages/plexus/src/Digraph/SvgEdge.tsx
  packages/plexus/src/Digraph/SvgEdges.tsx
  packages/plexus/src/types/index.tsx
  packages/plexus/src/zoom/utils.tsx
  yarn.lock
Labels: changelog:bugfix-or-minor-feature

#2063 Updated Default Configuration for Deep Dependency Graph
  packages/jaeger-ui/src/components/DeepDependencies/Header/LayoutSettings/index.test.js
  packages/jaeger-ui/src/components/DeepDependencies/Header/LayoutSettings/index.tsx
Labels: changelog:new-feature

#2066 refac: migrate `ExamplesLink` and `EmphasizedNode` components from enzyme to RTL
  packages/jaeger-ui/src/components/common/EmphasizedNode.test.js
  packages/jaeger-ui/src/components/common/EmphasizedNode.tsx
  packages/jaeger-ui/src/components/common/ExamplesLink.test.js
  packages/jaeger-ui/src/components/common/ExamplesLink.tsx
  packages/jaeger-ui/src/components/common/__snapshots__/EmphasizedNode.test.js.snap
  packages/jaeger-ui/src/components/common/__snapshots__/ExamplesLink.test.js.snap
Labels: changelog:test

#2065 migrate: Migrate ExternalLinks component from enzyme to RTL
  packages/jaeger-ui/src/components/common/ExternalLinks.test.js
  packages/jaeger-ui/src/components/common/ExternalLinks.tsx
Labels: changelog:test

#2064 fix: Fix some linting warnings
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.track.tsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.tsx
  packages/jaeger-ui/src/components/TracePage/ScrollManager.tsx
  packages/jaeger-ui/src/components/TracePage/TraceGraph/calculateTraceDagEV.tsx
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/KeyboardShortcutsHelp.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianText.tsx
  packages/jaeger-ui/src/model/trace-dag/TraceDag.tsx
  packages/jaeger-ui/src/reducers/metrics.tsx
  packages/jaeger-ui/src/types/api-error.tsx
  packages/jaeger-ui/src/types/metrics.tsx
  packages/jaeger-ui/src/types/trace.tsx
  packages/jaeger-ui/src/utils/DraggableManager/demo/DraggableManagerDemo.tsx
Labels: changelog:ci

#2068 fix: deprecate `set_output` from GitHub workflow
  .github/workflows/ci-label-check.yml
Labels: changelog:ci

#2070 Refac: Migrate 3 components from Enzyme to RTL
  packages/jaeger-ui/src/components/common/CircularProgressbar.test.js
  packages/jaeger-ui/src/components/common/CircularProgressbar.tsx
  packages/jaeger-ui/src/components/common/ErrorMessage.test.js
  packages/jaeger-ui/src/components/common/ErrorMessage.tsx
  packages/jaeger-ui/src/components/common/TraceName.test.js
  packages/jaeger-ui/src/components/common/TraceName.tsx
  packages/jaeger-ui/src/components/common/__snapshots__/CircularProgressbar.test.js.snap
  packages/jaeger-ui/src/components/common/__snapshots__/ErrorMessage.test.js.snap
  packages/jaeger-ui/src/components/common/__snapshots__/TraceName.test.js.snap
Labels: changelog:test

#2079 fix: Move `@types` packages from `dependencies` to `devDependencies`
  packages/jaeger-ui/package.json
Labels: changelog:dependencies

#2071 feat: remove `ReactGA` and migrate to `GA4` for tracking
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/utils/tracking/ga.test.js
  packages/jaeger-ui/src/utils/tracking/ga.tsx
  packages/jaeger-ui/src/utils/tracking/utils.test.js
  packages/jaeger-ui/src/utils/tracking/utils.tsx
  yarn.lock
Labels: changelog:bugfix-or-minor-feature
