Repository jaegertracing/jaeger-ui, pull requests merged in 2023-10, with the labels that each got.

#1897 CI: Add the label-check workflow to verify changelog labels on each PR
  .github/dependabot.yml
  .github/workflows/ci-label-check.yml
Labels: changelog:ci

#1902 Added tooltip when hovered on header column of TraceStatistics view
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/index.tsx
Labels: changelog:new-feature

#1871 Add tooltip when hovering Critical Path
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBar.css
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBar.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx
Labels: changelog:new-feature

#1901 [Refactor]: Enhancement to selfTime calculation logic in TraceStatistics view
  packages/jaeger-ui/src/components/TracePage/CriticalPath/testCases/test3.js
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.test.js
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.tsx
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValuesTestTrace/traceWithOverlappingChildrenLongerThanParent.json
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValuesTestTrace/traceWithSingleChildLongerThanParentAndStartsAfterParent.json
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValuesTestTrace/traceWithTwoNonOverlappingChildren.json
Labels: changelog:bugfix-or-minor-feature

#1907 Upgrade ant-design to v5.x
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/App/TopNav.css
  packages/jaeger-ui/src/components/App/TopNav.tsx
  packages/jaeger-ui/src/components/App/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/App/index.jsx
  packages/jaeger-ui/src/components/DeepDependencies/Header/LayoutSettings/index.tsx
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/QualityMetrics/__snapshots__/Header.test.js.snap
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.css
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/__snapshots__/CohortTable.test.js.snap
  packages/jaeger-ui/src/components/TracePage/ArchiveNotifier/index.test.js
  packages/jaeger-ui/src/components/TracePage/ArchiveNotifier/index.tsx
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/__snapshots__/KeyboardShortcutsHelp.test.js.snap
  packages/jaeger-ui/src/components/TracePage/TraceSpanView/index.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/ReferencesButton.tsx
  packages/jaeger-ui/src/components/common/CopyIcon.tsx
  packages/jaeger-ui/src/components/common/DetailsCard/__snapshots__/DetailTable.test.js.snap
  packages/jaeger-ui/src/components/common/SearchableSelect.tsx
  packages/jaeger-ui/src/components/common/__snapshots__/SearchableSelect.test.js.snap
  packages/jaeger-ui/src/components/common/__snapshots__/UiFindInput.test.js.snap
  packages/jaeger-ui/src/components/common/utils.css
  packages/jaeger-ui/src/utils/__snapshots__/redux-form-field-adapter.test.js.snap
  packages/jaeger-ui/vite.config.ts
  packages/plexus/package.json
  yarn.lock
Labels: changelog:bugfix-or-minor-feature

#1913 Fix linting warnings for all no-unused-vars
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/AltViewOptions.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx
Labels: changelog:skip

#1916 Fix linting warnings for Function, Boolean and String types
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/index.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/utils.tsx
  packages/jaeger-ui/src/model/ddg/transformTracesToPaths.tsx
  packages/jaeger-ui/src/types/config.tsx
  packages/jaeger-ui/src/utils/TreeNode.tsx
Labels: changelog:skip

#1926 Add better documentation on injecting configuration
  packages/jaeger-ui/README.md
  packages/jaeger-ui/index.html
  packages/jaeger-ui/src/types/config.tsx
Labels: changelog:skip
