Repository jaegertracing/jaeger-ui, pull requests merged in 2023-11, with the labels that each got.

#1927 Upgrade @types/react to v18.x latest
  package.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/common/DetailsCard/DetailTable.tsx
  packages/plexus/package.json
  packages/plexus/src/Digraph/HtmlLayer.tsx
  packages/plexus/src/Digraph/SvgLayer.tsx
  yarn.lock
Labels: changelog:dependencies

#1936 Bump eslint-plugin-jsx-a11y from 6.7.1 to 6.8.0
  package.json
  yarn.lock
Labels: changelog:dependencies

#1938 Remove scripts/draft-release.py
  scripts/draft-release.py
Labels: changelog:skip

#1939 Hide next release template in expander
  CHANGELOG.md
Labels: changelog:skip

#1960 Migrate `TraceTimelineLink.test.js` from enzyme to RTL
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceTimelineLink.test.js
  packages/jaeger-ui/src/components/common/NewWindowIcon.tsx
Labels: changelog:test

#1959 refac: migrate ReferenceLink.test.js from enzyme to RTL
  packages/jaeger-ui/src/components/TracePage/url/ReferenceLink.test.js
Labels: changelog:test

#1961 refac: migrate `ChevronDown` from enzyme to RTL
  packages/jaeger-ui/src/components/DeepDependencies/Header/ChevronDown.test.js
Labels: changelog:test

#1963 Add link to FAQ explaining why service map is empty
  packages/jaeger-ui/src/components/DependencyGraph/index.jsx
Labels: changelog:bugfix-or-minor-feature

#1965 Relax pinned resolutions to allow dependabot upgrades
  package.json
  yarn.lock
Labels: changelog:dependencies

#1968 Remove yarn resolution for @types/react
  package.json
Labels: changelog:dependencies

#1970 Setup router compatibility package for react-router-dom v6 upgrade
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/index.jsx
  yarn.lock
Labels: changelog:dependencies

#1944 Make ArchiveTrace button auto-configurable
  packages/jaeger-ui/index.html
  packages/jaeger-ui/src/components/TracePage/index.test.js
  packages/jaeger-ui/src/components/TracePage/index.tsx
  packages/jaeger-ui/src/constants/default-config.tsx
  packages/jaeger-ui/src/types/config.tsx
  packages/jaeger-ui/src/utils/config/get-config.test.js
  packages/jaeger-ui/src/utils/config/get-config.tsx
  packages/jaeger-ui/test/jest-per-test-setup.js
  packages/jaeger-ui/typings/custom.d.ts
Labels: changelog:new-feature

#1962 Migrate TraceDiffs/Header from enzyme to RTL
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceHeader.test.js
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceHeader.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/__snapshots__/TraceHeader.test.js.snap
Labels: changelog:test

#1974 Exit mergeChildrenCriticalPath early for an empty critical path
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx
Labels: changelog:bugfix-or-minor-feature

#1997 Remove lerna dependency
  .gitignore
  BUILD.md
  lerna.json
  package.json
  yarn.lock
Labels: changelog:dependencies, changelog:ci

#1998 Restore scripts/get-tracking-version.js deleted by accident
  scripts/get-tracking-version.js
Labels: changelog:ci

#1992 Change Vite config from CJS to ESM
  package.json
  packages/jaeger-ui/vite.config.mts
  packages/plexus/webpack-factory.js
Labels: changelog:ci

#1941 Speed up Trace Statistics view calculation
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.tsx
Labels: changelog:bugfix-or-minor-feature
