Repository jaegertracing/jaeger-ui, pull requests merged in 2024-11, with the labels that each got.

#2486 Prepare release 1.63.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2488 Bump cross-spawn to 7.0.5
  package-lock.json
Labels: changelog:dependencies

#2502 Fix babel dependencies in plexus repo
  .github/workflows/unit-tests.yml
  package-lock.json
  packages/plexus/package.json
Labels: changelog:dependencies

#2501 Allow formatting link parameter values as ISO date #2487
  packages/jaeger-ui/src/model/link-patterns.test.js
  packages/jaeger-ui/src/model/link-patterns.tsx
  packages/jaeger-ui/src/utils/link-formatting.test.js
  packages/jaeger-ui/src/utils/link-formatting.tsx
  packages/jaeger-ui/src/utils/stringSupplant.tsx
Labels: changelog:bugfix-or-minor-feature
