Repository jaegertracing/jaeger-ui, pull requests merged in 2024-01, with the labels that each got.

#2080 feat: remove `is-promise` library
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/actions/jaeger-api.js
  packages/jaeger-ui/src/actions/jaeger-api.test.js
  packages/jaeger-ui/src/utils/date.test.js
  packages/jaeger-ui/src/utils/readJsonFile.test.js
  packages/jaeger-ui/src/utils/readJsonFile.tsx
  yarn.lock
Labels: changelog:bugfix-or-minor-feature

#2091 Use fake/fixed date in unit tests
  packages/jaeger-ui/src/utils/date.test.js
Labels: changelog:test

#2089 Fix broken Hot Reload of Plexus Package
  packages/jaeger-ui/src/components/TracePage/TraceGraph/TraceGraph.tsx
  packages/jaeger-ui/vite.config.mts
Labels: changelog:bugfix-or-minor-feature

#2096 setup OSSF Scorecard workflow
  .github/workflows/codeql.yml
  .github/workflows/lint-build.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/unit-tests.yml
  README.md
Labels: changelog:ci

#2097 Prepare release v1.37.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2072 [Feature]: Add zoom in/out controls to Plexus graphs
  packages/jaeger-ui/src/components/common/utils.css
  packages/plexus/package.json
  packages/plexus/src/zoom/MiniMap.tsx
  packages/plexus/src/zoom/ZoomManager.tsx
  packages/plexus/src/zoom/resetZoomIcon.tsx
Labels: changelog:new-feature

#2133 Fix temp files for depcheck
  scripts/run-depcheck.sh
Labels: changelog:test

#2134 Upgrade react-icons to v5 without causing test failures.
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
  packages/plexus/package.json
  yarn.lock
Labels: changelog:dependencies

#2135 Use import from /dist/ instead of symlink
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.jsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/react-vis.css
Labels: changelog:bugfix-or-minor-feature
