Repository jaegertracing/jaeger-ui, pull requests merged in 2024-04, with the labels that each got.

#2237 Prepare release 1.40.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2274 Require Node version 20+
  .eslintignore
  .eslintrc.js
  .github/workflows/lint-build.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  .npmrc
  .nvmrc
  package.json
Labels: changelog:bugfix-or-minor-feature

#2269 [chore]: Bump follow-redirects from 1.15.4 to 1.15.6
  yarn.lock
Labels: changelog:dependencies

#2268 Add build for IBMz
  .github/workflows/Dockerfile
  .github/workflows/s390x-build.yaml
  package.json
  yarn.lock
Labels: changelog:skip

#2275 Improve trace page title with data and unique emoji (fixes #2256)
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/TracePageHeader.tsx
  packages/jaeger-ui/src/model/find-trace-page-header-parts.test.js
  packages/jaeger-ui/src/model/trace-viewer.tsx
  packages/jaeger-ui/src/model/transform-trace-data.tsx
  packages/jaeger-ui/src/types/trace.tsx
Labels: changelog:bugfix-or-minor-feature
