Repository jaegertracing/jaeger-ui, pull requests merged in 2024-03, with the labels that each got.

#2191 Gracefully handle spans without logs field
  packages/jaeger-ui/src/utils/filter-spans.test.js
  packages/jaeger-ui/src/utils/filter-spans.tsx
Labels: changelog:bugfix-or-minor-feature

#2145 Support uploading traces in OpenTelemetry format (OTLP JSON)
  packages/jaeger-ui/src/api/jaeger.js
  packages/jaeger-ui/src/api/jaeger.test.js
  packages/jaeger-ui/src/utils/fixtures/otlp2jaeger-in-error.json
  packages/jaeger-ui/src/utils/fixtures/otlp2jaeger-in.json
  packages/jaeger-ui/src/utils/fixtures/otlp2jaeger-out.json
  packages/jaeger-ui/src/utils/readJsonFile.test.js
  packages/jaeger-ui/src/utils/readJsonFile.tsx
Labels: changelog:new-feature

#2193 Prepare release v1.39.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2200 Fix upload file into search page unnecessary POST
  packages/jaeger-ui/src/components/SearchTracePage/FileLoader.tsx
Labels: changelog:bugfix-or-minor-feature

#2202 Feat: add `depcheck 1.4.7` in `package.json`
  .github/workflows/lint-build.yml
  package.json
  scripts/run-depcheck.sh
  yarn.lock
Labels: changelog:ci

#2211 Make ScatterPlot y-axis margin wider to fit longer durations
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.jsx
Labels: changelog:bugfix-or-minor-feature

#2224 Fix HTML code for apostrophe
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.jsx
Labels: changelog:bugfix-or-minor-feature
