Repository jaegertracing/jaeger-ui, pull requests merged in 2024-05, with the labels that each got.

#2295 Prepare release 1.57.0
  CHANGELOG.md
  Makefile
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2296 Github Actions Added to Block PRs from fork/main branch
  .github/workflows/lint-build.yml
Labels: changelog:ci

#2297 Document how to debug unit tests in VSCode
  README.md
Labels: changelog:bugfix-or-minor-feature
