Repository jaegertracing/jaeger-ui, pull requests merged in 2024-10, with the labels that each got.

#2461 Support uploads of .jsonl files
  packages/jaeger-ui/src/components/SearchTracePage/FileLoader.tsx
  packages/jaeger-ui/src/components/SearchTracePage/__snapshots__/FileLoader.test.js.snap
Labels: changelog:bugfix-or-minor-feature

#2463 Prepare release v1.62.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2465 Update antd to 5.21.3
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/App/TopNav.css
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/index.css
  packages/jaeger-ui/src/components/common/DetailsCard/__snapshots__/DetailList.test.js.snap
  yarn.lock
Labels: changelog:dependencies

#2464 Update @types/react to 18.3.11
  packages/jaeger-ui/package.json
  packages/plexus/package.json
  packages/plexus/src/DirectedGraph/builtins/Node.tsx
  yarn.lock
Labels: changelog:dependencies

#2470 Upgrade all dependencies by regenerating lockfile
  package.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItemTitle.tsx
  packages/jaeger-ui/src/components/TracePage/index.tsx
  packages/jaeger-ui/src/types/index.tsx
  yarn.lock
Labels: changelog:dependencies

#2462 Migrate from yarn v1 to npm
  .github/workflows/Dockerfile
  .github/workflows/lint-build.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  .npmrc
  BUILD.md
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/utils/tracking/README.md
  packages/plexus/BUILD.md
  packages/plexus/package.json
  yarn.lock
Labels: changelog:bugfix-or-minor-feature

#2478 Add missing integrity checks to package-lock.json
  package-lock.json
Labels: changelog:dependencies

#2481 Run s390x build on push to main only
  .github/workflows/s390x-build.yaml
Labels: changelog:ci
