Repository jaegertracing/jaeger-ui, pull requests merged in 2025-05, with the labels that each got.

#2742 Migrate ResultItem tests
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx
Labels: changelog:test

#2731 Add ability to use typescript in tests
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/generateDropdownValue.test.ts
  packages/jaeger-ui/tsconfig.json
  scripts/generateDepcheckrcJaegerUI.js
Labels: changelog:ci

#2762 Prepare release 1.69.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2763 Upgrade @typescript-eslint/eslint-plugin to latest version
  .eslintrc.js
  package-lock.json
  package.json
  packages/jaeger-ui/src/reducers/metrics.mock.js
  packages/plexus/package.json
Labels: changelog:dependencies

#2749 Fix DependencyGraph dag extra render
  packages/jaeger-ui/src/components/DependencyGraph/DAG.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAG.tsx
  packages/jaeger-ui/src/components/DependencyGraph/index.test.js
  packages/jaeger-ui/src/components/DependencyGraph/index.tsx
  packages/jaeger-ui/tsconfig.lint.json
Labels: changelog:bugfix-or-minor-feature

#2775 [Fix]: Reduce default minimum allowed zoom
  packages/plexus/src/zoom/utils.tsx
Labels: changelog:bugfix-or-minor-feature

#2776 docs: remove redundant UI config link from README
  README.md
Labels: changelog:skip

#2772 Replace deprecated `overlayClassName` with `classNames.root`
  packages/jaeger-ui/src/components/DeepDependencies/Header/index.tsx
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/index.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/__snapshots__/renderNode.test.js.snap
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/renderNode.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceDiffHeader.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/__snapshots__/TraceDiffHeader.test.js.snap
  packages/jaeger-ui/src/components/TracePage/TraceGraph/OpNode.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/ReferencesButton.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBar.tsx
  packages/jaeger-ui/src/components/common/DetailsCard/DetailTableDropdown.tsx
  packages/jaeger-ui/src/components/common/DetailsCard/__snapshots__/DetailTableDropdown.test.js.snap
  packages/jaeger-ui/src/components/common/NameSelector.tsx
Labels: changelog:bugfix-or-minor-feature

#2788 test: add test coverage for button click handler
  packages/jaeger-ui/src/components/Monitor/EmptyState/index.test.js
Labels: changelog:test

#2790 feat: convert MonitorATMEmptyState to a functional component
  packages/jaeger-ui/src/components/Monitor/EmptyState/index.tsx
Labels: changelog:bugfix-or-minor-feature

#2798 test: achieve 100% coverage for SearchResults components and improve test reliability
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItemTitle.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.test.js
Labels: changelog:test

#2814 Allow json logs to occupy entire available width
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/KeyValuesTable.css
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/index.css
Labels: changelog:bugfix-or-minor-feature

#2812 Fix array return pattern in `LabeledList` component
  packages/jaeger-ui/src/components/common/LabeledList.tsx
Labels: changelog:bugfix-or-minor-feature

#2811 test(calculateTraceDagEV): improve coverage and add mapFollowsFrom unit tests
  packages/jaeger-ui/src/components/TracePage/TraceGraph/calculateTraceDagEV.test.js
  packages/jaeger-ui/src/components/TracePage/TraceGraph/calculateTraceDagEV.tsx
Labels: changelog:test

#2767 Rewrite computeSelfTime to improve performance on Trace Statistics page
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.tsx
Labels: changelog:bugfix-or-minor-feature

#2824 Refactor CanvasSpanGraph to Functional Component and Improve test coverage
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/SpanGraph/CanvasSpanGraph.test.js
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/SpanGraph/CanvasSpanGraph.tsx
Labels: changelog:refactoring

#2816 Migrate TraceTimelineViewerImpl to a functional component
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/index.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/index.tsx
Labels: changelog:refactoring

#2839 test: Migrate AccordianLogs tests from Enzyme to RTL
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianLogs.test.js
Labels: changelog:test

#2806 Enhance TraceDiff UI components
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/TraceDiffGraph.css
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/TraceDiffGraph.test.js
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/TraceDiffGraph.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceDiffHeader.css
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceDiffHeader.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceHeader.css
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceHeader.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/__snapshots__/TraceDiffHeader.test.js.snap
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx
  packages/jaeger-ui/src/constants/default-config.tsx
  packages/jaeger-ui/src/types/config.tsx
Labels: changelog:bugfix-or-minor-feature

#2827 refactor: SpanDetailRow to functional component
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetailRow.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetailRow.tsx
Labels: changelog:refactoring

#2844 feat: Filter logs based on the selected time range
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBar.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanBarRow.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianLogs.css
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianLogs.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianLogs.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/index.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetailRow.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx
Labels: changelog:bugfix-or-minor-feature

#2829 Migrate `FileLoader.test.js` and `DiffSelection.test.js` from Enzyme to RTL
  packages/jaeger-ui/src/components/SearchTracePage/FileLoader.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/DiffSelection.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/__snapshots__/DiffSelection.test.js.snap
  packages/jaeger-ui/src/components/SearchTracePage/__snapshots__/FileLoader.test.js.snap
Labels: changelog:test

#2847 test(SpanGraph): migrate test suite from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/SpanGraph/index.test.js
Labels: changelog:test
