Repository jaegertracing/jaeger-ui, pull requests merged in 2025-09, with the labels that each got.

#3054 Expand the logs automatically
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/index.test.js
  packages/jaeger-ui/src/components/DeepDependencies/traces.test.js
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/SpanGraph/index.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianLogs.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianLogs.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/DetailState.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/index.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx
  packages/jaeger-ui/src/utils/withRouteProps.test.js
Labels: changelog:bugfix-or-minor-feature

#3068 Add new test file for span to cover the getParent function
  packages/jaeger-ui/src/model/span.test.js
Labels: changelog:test

#623 Tighten TraceArchive type to more strictly enforce correct state
  packages/jaeger-ui/src/components/TracePage/ArchiveNotifier/duck.tsx
  packages/jaeger-ui/src/components/TracePage/ArchiveNotifier/index.tsx
  packages/jaeger-ui/src/types/archive.tsx
Labels: changelog:refactoring

#3071 Convert SeachResults{ResultItem, ResultItemTitle} to functional components
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItemTitle.tsx
Labels: changelog:refactoring

#3082 Convert TraceDiff/TraceDiffHeader {CohortTable, TraceDiffHeader} to functional component
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/CohortTable.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceDiffHeader.tsx
Labels: changelog:refactoring

#3076 convert SearchResults/DiffSelection to functional component and improved testcases
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/DiffSelection.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/DiffSelection.tsx
Labels: changelog:refactoring

#3083 Convert FilteredList/index.tsx from class to functional component
  packages/jaeger-ui/src/components/common/FilteredList/index.test.js
  packages/jaeger-ui/src/components/common/FilteredList/index.tsx
  packages/jaeger-ui/src/components/common/NameSelector.tsx
Labels: changelog:refactoring

#3004 Convert ServicesView/index to functional component
  packages/jaeger-ui/src/components/Monitor/ServicesView/index.tsx
Labels: changelog:refactoring

#3097 Update to modern JSX transform
  packages/jaeger-ui/test/babel-transform.js
  packages/jaeger-ui/tsconfig.json
  packages/plexus/babel.config.js
  tsconfig.json
Labels: changelog:refactoring
