Repository jaegertracing/jaeger-ui, pull requests merged in 2025-07, with the labels that each got.

#2898 test: Migrate KeyValuesTable Tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/KeyValuesTable.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/__snapshots__/KeyValuesTable.test.js.snap
Labels: changelog:test

#2859 Migrate `QualityMetrics/Header.test.js` from Enzyme to RTL
  packages/jaeger-ui/src/components/QualityMetrics/Header.test.js
  packages/jaeger-ui/src/components/QualityMetrics/__snapshots__/Header.test.js.snap
Labels: changelog:test

#2879 test: Migrate VerticalResizer test from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/common/VerticalResizer.test.js
  packages/jaeger-ui/src/components/common/VerticalResizer.tsx
Labels: changelog:test

#2899 Convert `ResultItemTitle.test.js` from Enzyme to RTL
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItemTitle.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/__snapshots__/ResultItemTitle.test.js.snap
Labels: changelog:test

#2919 Prepare release v1.71.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2842 Migrate `TraceGraph.test.js` from Enzyme to RTL
  packages/jaeger-ui/src/components/TracePage/TraceGraph/TraceGraph.test.js
  packages/jaeger-ui/src/components/TracePage/TraceGraph/TraceGraph.tsx
Labels: changelog:test

#2918 test(header): migrate Header component tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/DeepDependencies/Header/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/DeepDependencies/Header/index.test.js
Labels: changelog:test

#2920 Fix eslint warnings in ddg component
  packages/jaeger-ui/src/actions/ddg.tsx
Labels: changelog:refactoring

#2917 test(graph): migrate Graph component tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/DeepDependencies/Graph/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/DeepDependencies/Graph/index.test.js
Labels: changelog:test

#2923 Fix bug when calculate GroupByOperation metrics
  packages/jaeger-ui/src/reducers/metrics.mock.js
  packages/jaeger-ui/src/reducers/metrics.tsx
Labels: changelog:bugfix-or-minor-feature

#2924 test: migrate TraceStatistics tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/index.test.js
Labels: changelog:test

#2921 Fix eslint warnings in path-agnostic-decorations component
  packages/jaeger-ui/src/actions/path-agnostic-decorations.tsx
Labels: changelog:skip

#2929 Convert `TraceIDSearchInput.tsx` from class component to functional component
  packages/jaeger-ui/src/components/App/TraceIDSearchInput.tsx
Labels: changelog:refactoring

#2928 Convert `operationDetailsTable/index.tsx` from class component to functional component
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/index.tsx
Labels: changelog:refactoring

#2915 Convert `QualityMetrics/Header.tsx` from class component to functional component
  packages/jaeger-ui/src/components/QualityMetrics/Header.test.js
  packages/jaeger-ui/src/components/QualityMetrics/Header.tsx
Labels: changelog:refactoring

#2953 test: migrate TraceDiffHeader tests from Enzyme to RTL
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceDiffHeader.test.js
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/__snapshots__/TraceDiffHeader.test.js.snap
Labels: changelog:test

#2956 test: Migrate <ViewingLayer> Tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/SpanGraph/ViewingLayer.test.js
Labels: changelog:test

#2954 Convet `UiFindInput.tsx` from class component to functional component
  packages/jaeger-ui/src/components/common/UiFindInput.test.js
  packages/jaeger-ui/src/components/common/UiFindInput.tsx
Labels: changelog:refactoring

#2930 Fix eslint warnings in jaeger.js, NotFound and TraceIDSearchInput component
  packages/jaeger-ui/src/api/jaeger.js
  packages/jaeger-ui/src/components/App/NotFound.tsx
  packages/jaeger-ui/src/components/App/TraceIDSearchInput.tsx
Labels: changelog:skip

#2957 Fix UI bug of convertServiceErrorRateToPercentages
  packages/jaeger-ui/src/components/Monitor/ServicesView/index.test.js
  packages/jaeger-ui/src/components/Monitor/ServicesView/index.tsx
Labels: changelog:bugfix-or-minor-feature

#2961 test: Migrate QualityMetrics Tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/QualityMetrics/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/QualityMetrics/index.test.js
Labels: changelog:test

#2965 Remove invalid nullable
  packages/jaeger-ui/typings/custom.d.ts
Labels: changelog:skip

#2964 Implemented the mouse-over popup functionality for the dots on the time series view
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.css
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.jsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.tsx
Labels: changelog:bugfix-or-minor-feature

#2960 Convert `SidePanel/index.tsx` from class component to functional component
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/index.test.js
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/index.tsx
Labels: changelog:refactoring

#2959 Convert `traces.tsx` from class component to functional component
  packages/jaeger-ui/src/components/DeepDependencies/traces.tsx
Labels: changelog:refactoring

#2967 Fix the DDG node tooltip position
  packages/jaeger-ui/src/components/DeepDependencies/Graph/DdgNodeContent/index.css
  packages/jaeger-ui/src/components/DeepDependencies/Graph/DdgNodeContent/index.test.js
  packages/jaeger-ui/src/components/DeepDependencies/Graph/DdgNodeContent/index.tsx
Labels: changelog:bugfix-or-minor-feature

#2968 Add code coverage explanation to README.md
  README.md
Labels: changelog:bugfix-or-minor-feature

#2955 test: Migrate SearchResults Component Tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.test.js
Labels: changelog:test

#2980 Upgrade redux-actions to 3.x
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/test/babel-transform.js
  scripts/generateDepcheckrcJaegerUI.js
Labels: changelog:bugfix-or-minor-feature

#2984 test: Migrate <MonitorATMServicesView> tests from Enzyme to RTL
  packages/jaeger-ui/src/components/Monitor/ServicesView/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/index.test.js
Labels: changelog:test

#2983 Setup Husky pre-commit hook with lint-staged
  .husky/pre-commit
  package-lock.json
  package.json
Labels: changelog:bugfix-or-minor-feature

#2995 Fix the issue of operation reset to all when reloading the Search screen
  packages/jaeger-ui/src/components/SearchTracePage/index.jsx
  packages/jaeger-ui/src/components/SearchTracePage/index.test.js
Labels: changelog:bugfix-or-minor-feature

#2998 Convert TraceDiffGraph.tsx from class to functional component
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/TraceDiffGraph.tsx
Labels: changelog:refactoring

#2999 Convert ArchiveNotifier/index to functional component
  packages/jaeger-ui/src/components/TracePage/ArchiveNotifier/index.tsx
Labels: changelog:refactoring
