Repository jaegertracing/jaeger-ui, pull requests merged in 2025-01, with the labels that each got.

#2537 [chore] Update redux and react-redux to latest version
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/TraceDiff/TraceDiff.test.js
  packages/jaeger-ui/src/types/index.tsx
Labels: changelog:dependencies

#2538 [fix]: Make Plexus demo work again
  package-lock.json
  packages/plexus/package.json
  packages/plexus/webpack-factory.js
Labels: changelog:bugfix-or-minor-feature

#2546 Update paths for release note scripts
  Makefile
Labels: changelog:skip

#2550 [chore]: upgrade vite group
  package-lock.json
  packages/jaeger-ui/package.json
Labels: changelog:dependencies

#2553 [revert]: revert redux and react-redux dependency upgrades
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/TraceDiff/TraceDiff.test.js
  packages/jaeger-ui/src/types/index.tsx
Labels: changelog:dependencies

#2548 [clean-up]: Remove deprecated plexus/DirectedGraph
  packages/plexus/README.md
  packages/plexus/demo/src/SimpleGraph.tsx
  packages/plexus/demo/src/UxEdges.tsx
  packages/plexus/demo/src/index.tsx
  packages/plexus/src/Digraph/index.tsx
  packages/plexus/src/DirectedGraph/DirectedGraph.tsx
  packages/plexus/src/DirectedGraph/builtins/EdgeArrow.tsx
  packages/plexus/src/DirectedGraph/builtins/EdgeArrowDef.tsx
  packages/plexus/src/DirectedGraph/builtins/EdgePath.tsx
  packages/plexus/src/DirectedGraph/builtins/EdgesContainer.tsx
  packages/plexus/src/DirectedGraph/builtins/Node.tsx
  packages/plexus/src/DirectedGraph/builtins/PureEdges.tsx
  packages/plexus/src/DirectedGraph/builtins/PureNodes.tsx
  packages/plexus/src/DirectedGraph/index.tsx
  packages/plexus/src/DirectedGraph/prop-factories/classNameIsSmall.tsx
  packages/plexus/src/DirectedGraph/prop-factories/mergePropSetters.tsx
  packages/plexus/src/DirectedGraph/prop-factories/scaledStrokeWidth.tsx
  packages/plexus/src/DirectedGraph/types.tsx
  packages/plexus/src/index.tsx
Labels: changelog:bugfix-or-minor-feature

#2559 Prepare release v1.65.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2566 fix TraceDiff graph pan and zoom issue
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/TraceDiffGraph.tsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffGraph/__snapshots__/TraceDiffGraph.test.js.snap
Labels: changelog:bugfix-or-minor-feature

#2562 [fix]: Remove redux-form dependency from Monitor page
  packages/jaeger-ui/src/components/Monitor/ServicesView/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/index.test.js
  packages/jaeger-ui/src/components/Monitor/ServicesView/index.tsx
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/index.tsx
  packages/jaeger-ui/src/reducers/metrics.mock.js
  packages/jaeger-ui/src/reducers/metrics.tsx
  packages/jaeger-ui/src/types/metrics.tsx
Labels: changelog:bugfix-or-minor-feature

#2568 Update: plexus to use @viz-js/viz v3
  package-lock.json
  packages/plexus/package.json
  packages/plexus/src/LayoutManager/getLayout.tsx
  packages/plexus/src/LayoutManager/layout.worker.tsx
  packages/plexus/typings/custom.d.ts
  packages/plexus/typings/index.d.ts
Labels: changelog:dependencies

#2571 Fix: Deep clone trace data for consistency
  packages/jaeger-ui/src/components/TracePage/TraceFlamegraph/index.tsx
Labels: changelog:bugfix-or-minor-feature

#2579 Upgrade antd to v5.23.0 from v5.21.3
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
Labels: changelog:dependencies

#2569 [fix]: Remove redux-form dependency from sort selector
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.track.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.track.tsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.test.js
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.tsx
  packages/jaeger-ui/src/components/SearchTracePage/index.jsx
  packages/jaeger-ui/src/components/SearchTracePage/index.test.js
  packages/jaeger-ui/src/middlewares/track.tsx
Labels: changelog:bugfix-or-minor-feature

#2586 [ci]: Add workflow to guard against growing bundle size
  .github/workflows/check_bundle.yml
Labels: changelog:ci

#2591 [CI] Fix cache resolution and syntax in check binary size workflow
  .github/workflows/check_bundle.yml
Labels: changelog:ci

#2593 [Deps]: Remove dependency on redux-form
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.jsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js
  packages/jaeger-ui/src/components/SearchTracePage/index.test.js
  packages/jaeger-ui/src/constants/search-form.tsx
  packages/jaeger-ui/src/middlewares/index.js
  packages/jaeger-ui/src/middlewares/index.test.js
  packages/jaeger-ui/src/reducers/index.js
  packages/jaeger-ui/src/utils/ValidatedFormField.css
  packages/jaeger-ui/src/utils/ValidatedFormField.test.js
  packages/jaeger-ui/src/utils/ValidatedFormField.tsx
  packages/jaeger-ui/src/utils/__snapshots__/redux-form-field-adapter.test.js.snap
  packages/jaeger-ui/src/utils/configure-store.test.js
  packages/jaeger-ui/src/utils/redux-form-field-adapter.test.js
  packages/jaeger-ui/src/utils/redux-form-field-adapter.tsx
Labels: changelog:bugfix-or-minor-feature

#2600 [fix]: Disable submit button on invalid minDuration or maxDuration
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.jsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js
  packages/jaeger-ui/src/constants/search-form.tsx
  packages/jaeger-ui/src/middlewares/index.js
  packages/jaeger-ui/src/middlewares/index.test.js
Labels: changelog:bugfix-or-minor-feature

#2607 Pin @sentry/browser from ^8.18.0 to 8.50.0
  packages/jaeger-ui/package.json
Labels: changelog:dependencies

#2601 [LoadingIndicator]: Replace defaultProps with destructuring
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/__snapshots__/DetailsPanel.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/__snapshots__/serviceGraph.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/QualityMetrics/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/common/LoadingIndicator.tsx
Labels: changelog:bugfix-or-minor-feature

#2609 Remove defaultProps from ErrorMessage & NewWindowIcon
  packages/jaeger-ui/src/components/DeepDependencies/Graph/DdgNodeContent/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/__snapshots__/DetailsPanel.test.js.snap
  packages/jaeger-ui/src/components/QualityMetrics/__snapshots__/MetricCard.test.js.snap
  packages/jaeger-ui/src/components/QualityMetrics/__snapshots__/ScoreCard.test.js.snap
  packages/jaeger-ui/src/components/common/ErrorMessage.tsx
  packages/jaeger-ui/src/components/common/NewWindowIcon.tsx
Labels: changelog:bugfix-or-minor-feature

#2602 [QualityMetrics/MetricCard] Migrate enzyme tests to RTL
  packages/jaeger-ui/src/components/QualityMetrics/MetricCard.test.js
  packages/jaeger-ui/src/components/QualityMetrics/MetricCard.tsx
  packages/jaeger-ui/src/components/QualityMetrics/__snapshots__/MetricCard.test.js.snap
Labels: changelog:test

#2623 [deps]: Upgrade redux and react-redux to latest version
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/TraceDiff/TraceDiff.test.js
  packages/jaeger-ui/src/types/index.tsx
Labels: changelog:dependencies

#2629 Enable workflows to run in merge queue
  .github/workflows/check_bundle.yml
  .github/workflows/ci-label-check.yml
  .github/workflows/codeql.yml
  .github/workflows/lint-build.yml
  .github/workflows/unit-tests.yml
Labels: changelog:ci

#2630 Don't run codeql from merge queue
  .github/workflows/codeql.yml
Labels: changelog:ci

#2631 Don't run label check in merge queue
  .github/workflows/ci-label-check.yml
Labels: changelog:ci

#2632 Add fake DCO check for merge queue events
  .github/workflows/dco_merge_group.yml
Labels: changelog:ci

#2633 Rename dco->DCO check
  .github/workflows/dco_merge_group.yml
Labels: changelog:ci

#2635 Remove unused matrix from codeql workflow
  .github/workflows/codeql.yml
Labels: changelog:ci

#2611 Remove defaultProps fromt BreakableText.tsx
  packages/jaeger-ui/src/components/DeepDependencies/Graph/DdgNodeContent/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/__snapshots__/DetailsPanel.test.js.snap
  packages/jaeger-ui/src/components/common/BreakableText.tsx
  packages/jaeger-ui/src/components/common/__snapshots__/NameSelector.test.js.snap
Labels: changelog:bugfix-or-minor-feature

#2613 Remove defaultProps from AccordianLogs.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianLogs.tsx
Labels: changelog:bugfix-or-minor-feature

#2620 Remove defaultProps from TraceHeader.jsx
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceHeader.tsx
Labels: changelog:bugfix-or-minor-feature

#2616 Remove defaultProps from TimelineRow.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/TimelineRow.tsx
Labels: changelog:bugfix-or-minor-feature

#2617 Remove defaultProps from Ticks.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/Ticks.tsx
Labels: changelog:bugfix-or-minor-feature

#2612 Remove defaultProps from AccordianText.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianText.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianText.tsx
Labels: changelog:bugfix-or-minor-feature

#2638 Migrate EmpasizedNode from class based to function based component
  packages/jaeger-ui/src/components/common/EmphasizedNode.tsx
Labels: changelog:bugfix-or-minor-feature

#2618 Remove defaultProps from ScatterPlot.jsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.jsx
Labels: changelog:bugfix-or-minor-feature

#2615 Remove defaultProps from MiniMap.tsx
  packages/plexus/src/zoom/MiniMap.tsx
Labels: changelog:bugfix-or-minor-feature
