Repository jaegertracing/jaeger-ui, pull requests merged in 2025-03, with the labels that each got.

#2679 Replace react-vis with recharts
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/Monitor/ServicesView/__snapshots__/serviceGraph.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/opsGraph.test.js.snap
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/opsGraph.css
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/opsGraph.test.js
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/opsGraph.tsx
  packages/jaeger-ui/src/components/Monitor/ServicesView/serviceGraph.css
  packages/jaeger-ui/src/components/Monitor/ServicesView/serviceGraph.test.js
  packages/jaeger-ui/src/components/Monitor/ServicesView/serviceGraph.tsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.css
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.jsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ScatterPlot.test.js
Labels: changelog:bugfix-or-minor-feature

#2688 Prepare release v1.67.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2689 Add Handling or error for invalid json formats and tests
  packages/jaeger-ui/src/components/SearchTracePage/index.jsx
  packages/jaeger-ui/src/reducers/trace.js
  packages/jaeger-ui/src/reducers/trace.test.js
Labels: changelog:bugfix-or-minor-feature

#2690 Add sfdp engine in @jaegertracing/plexus
  packages/jaeger-ui/src/components/DependencyGraph/DAG.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAG.tsx
  packages/plexus/src/LayoutManager/Coordinator.tsx
  packages/plexus/src/LayoutManager/dot/conv-coord.tsx
  packages/plexus/src/LayoutManager/dot/toDot.tsx
  packages/plexus/src/LayoutManager/getLayout.tsx
  packages/plexus/src/LayoutManager/types.tsx
Labels: changelog:bugfix-or-minor-feature

#2693 [refactor] Convert ExamplesLink to a functional component
  packages/jaeger-ui/src/components/common/ExamplesLink.tsx
Labels: changelog:refactoring

#2691 Add Depth and Layout controls and sfdp layout to DAG view
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/DependencyGraph/DAG.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAG.tsx
  packages/jaeger-ui/src/components/DependencyGraph/DAGOptions.css
  packages/jaeger-ui/src/components/DependencyGraph/DAGOptions.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAGOptions.tsx
  packages/jaeger-ui/src/components/DependencyGraph/DependencyForceGraph.jsx
  packages/jaeger-ui/src/components/DependencyGraph/DependencyForceGraph.test.js
  packages/jaeger-ui/src/components/DependencyGraph/ForceGraphArrowLink.test.js
  packages/jaeger-ui/src/components/DependencyGraph/ForceGraphArrowLink.tsx
  packages/jaeger-ui/src/components/DependencyGraph/index.css
  packages/jaeger-ui/src/components/DependencyGraph/index.jsx
  packages/jaeger-ui/src/components/DependencyGraph/index.test.js
  packages/jaeger-ui/src/constants/index.tsx
  packages/jaeger-ui/tsconfig.lint.json
  packages/jaeger-ui/typings/custom.d.ts
Labels: changelog:bugfix-or-minor-feature

#2695 [refactor] Convert CircularProgressbar to a functional component
  packages/jaeger-ui/src/components/common/CircularProgressbar.tsx
Labels: changelog:refactoring

#2698 Add sample graph data when in dev mode
  packages/jaeger-ui/src/components/DependencyGraph/DAG.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAG.tsx
  packages/jaeger-ui/src/components/DependencyGraph/DAGOptions.css
  packages/jaeger-ui/src/components/DependencyGraph/DAGOptions.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAGOptions.tsx
  packages/jaeger-ui/src/components/DependencyGraph/dag.css
  packages/jaeger-ui/src/components/DependencyGraph/index.jsx
  packages/jaeger-ui/src/components/DependencyGraph/index.test.js
  packages/jaeger-ui/src/components/DependencyGraph/sample_data/large.json
  packages/jaeger-ui/src/components/DependencyGraph/sample_data/small.json
  packages/jaeger-ui/src/constants/index.tsx
  packages/jaeger-ui/tsconfig.lint.json
  packages/jaeger-ui/typings/custom.d.ts
  scripts/utils/parse-traces.js
Labels: changelog:bugfix-or-minor-feature
