Repository jaegertracing/jaeger-ui, pull requests merged in 2025-08, with the labels that each got.

#3006 Prepare release v.1.72.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#3003 test: Migrate DAG tests to React Testing Library
  packages/jaeger-ui/src/components/DependencyGraph/DAG.test.js
  packages/jaeger-ui/src/components/DependencyGraph/DAG.tsx
Labels: changelog:test

#3007 test: Migrate SearchForm Tests from Enzyme to React Testing Library
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js
Labels: changelog:test

#3009 test: Migrate JaegerUIApp Component Tests to React Testing Library
  packages/jaeger-ui/src/components/App/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/components/App/index.test.js
Labels: changelog:test

#3010 chore: remove Enzyme and related dependencies
  package-lock.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/utils/ReactShallowRenderer.test.js
  packages/jaeger-ui/test/jest-per-test-setup.js
Labels: changelog:dependencies

#3024 Upgrade to @babel/plugin transform class properties
  package-lock.json
  packages/jaeger-ui/package.json
  packages/plexus/babel.config.js
  packages/plexus/package.json
Labels: changelog:dependencies

#3025 test: fix GA test and increase coverage
  packages/jaeger-ui/src/utils/tracking/ga.test.js
Labels: changelog:test

#3034 Highlight active mode button in TraceGraph
  packages/jaeger-ui/src/components/TracePage/TraceGraph/TraceGraph.css
  packages/jaeger-ui/src/components/TracePage/TraceGraph/TraceGraph.tsx
Labels: changelog:bugfix-or-minor-feature

#3040 Upgrade project to React 19
  package-lock.json
  package.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/DeepDependencies/SidePanel/index.test.js
  packages/jaeger-ui/src/components/DeepDependencies/traces.test.js
  packages/jaeger-ui/src/components/Monitor/ServicesView/index.tsx
  packages/jaeger-ui/src/components/Monitor/ServicesView/serviceGraph.tsx
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/SpanGraph/index.test.js
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/index.test.js
  packages/jaeger-ui/src/components/TracePage/TraceStatistics/tableValues.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/TimelineHeaderRow/TimelineCollapser.tsx
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/TimelineHeaderRow/TimelineViewingLayer.tsx
  packages/jaeger-ui/src/components/TracePage/index.tsx
  packages/jaeger-ui/src/components/common/DetailsCard/DetailTableDropdown.tsx
  packages/jaeger-ui/src/components/common/FilteredList/index.tsx
  packages/jaeger-ui/src/components/common/RelativeDate.tsx
  packages/jaeger-ui/src/model/path-agnostic-decorations/__snapshots__/index.test.js.snap
  packages/jaeger-ui/src/model/path-agnostic-decorations/index.test.js
  packages/jaeger-ui/src/utils/withRouteProps.test.js
  packages/plexus/package.json
  packages/plexus/src/Digraph/MeasurableNode.tsx
  packages/plexus/src/Digraph/MeasurableNodesLayer.tsx
  packages/plexus/src/Digraph/index.tsx
  packages/plexus/tsconfig.json
Labels: changelog:new-feature

#2951 Convert `VerticalResizer.tsx` from class component to functional component
  packages/jaeger-ui/src/components/common/VerticalResizer.test.js
  packages/jaeger-ui/src/components/common/VerticalResizer.tsx
Labels: changelog:refactoring

#3048 Make the scrollbar always visible in lookback dropdown
  packages/jaeger-ui/src/components/SearchTracePage/SearchForm.css
Labels: changelog:bugfix-or-minor-feature

#3053 chore(eslint): upgrade @typescript-eslint/eslint-plugin & parser to v8.41.0
  eslint.config.js
  package-lock.json
  package.json
Labels: changelog:dependencies
