Repository jaegertracing/jaeger-ui, pull requests merged in 2025-02, with the labels that each got.

#2644 Prepare Release v1.66.0
  CHANGELOG.md
  packages/jaeger-ui/package.json
Labels: changelog:skip

#2646 Upgrade jsdom to v26 (latest)
  package-lock.json
  package.json
  packages/jaeger-ui/package.json
  packages/jaeger-ui/src/components/Monitor/ServicesView/operationDetailsTable/__snapshots__/index.test.js.snap
Labels: changelog:dependencies

#2536 Add config option to allow displaying full traceID
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItemTitle.tsx
  packages/jaeger-ui/src/components/SearchTracePage/SearchResults/__snapshots__/ResultItemTitle.test.js.snap
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceHeader.tsx
  packages/jaeger-ui/src/components/TracePage/TracePageHeader/TracePageHeader.tsx
  packages/jaeger-ui/src/components/common/TraceId.css
  packages/jaeger-ui/src/components/common/TraceId.test.js
  packages/jaeger-ui/src/components/common/TraceId.tsx
  packages/jaeger-ui/src/constants/default-config.tsx
  packages/jaeger-ui/src/types/config.tsx
Labels: changelog:bugfix-or-minor-feature

#2622 [TimelineRow]: Replace defaultProps with destructuring
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/TimelineRow.tsx
Labels: changelog:bugfix-or-minor-feature

#2621 [TraceHeader]: Replace defaultProps with destructuring
  packages/jaeger-ui/src/components/TraceDiff/TraceDiffHeader/TraceHeader.tsx
Labels: changelog:bugfix-or-minor-feature

#2666 [KeyValuesTable]: replace defaultProps with destructuring
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/KeyValuesTable.tsx
Labels: changelog:bugfix-or-minor-feature

#2665 Add markers to RELEASE.md
  RELEASE.md
Labels: changelog:skip

#2641 Make changes to allow for /api/quality-metrics to work
  packages/jaeger-ui/src/api/jaeger.js
  packages/jaeger-ui/src/api/jaeger.test.js
  packages/jaeger-ui/src/constants/default-config.tsx
  packages/jaeger-ui/src/types/config.tsx
  packages/jaeger-ui/src/utils/config/get-config.tsx
Labels: changelog:bugfix-or-minor-feature

#2667 [AccordianKeyValues]: replace defaultProps with destructuring
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianKeyValues.test.js
  packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/AccordianKeyValues.tsx
Labels: changelog:bugfix-or-minor-feature
